version: '3.8'
networks:
  qvision:
    name: micro

services:
  qvision_database:
    container_name: "qvisionDatabaseSqlServer2022"
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=qvision#2023
      - MSSQL_DB=Libros
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - ./qvision-logs:/app/App_Data/Logs
    networks:
      - qvision
  back_api:
    build: 
      context: ../
      dockerfile: Dockerfile
    container_name: qvisionWebapi
    restart: always
    ports:
      - "8001:80"
    depends_on:
      - qvision_database
    networks:
      - qvision
    